### PR TITLE
Change staging ari domain to the new one

### PR DESCRIPTION
**Pull request by javier-tercedor**
Related to https://github.com/weekendesk/product-management/issues/1234

### Context
This PR updates the staging url for standard ari communications for channel managers, to the new one which is using the proper certificate, because this one includes the domain `staging.weekendesk.com`.

### CODE REVIEW

**Review by deniswed — APPROVED** [review]

**Review by elicastilla1 — APPROVED** [review]

**Comment by ghost** [comment]
@javier-tercedor @cdelgado5 Have you checked with distributors about this change? They were using this URL for testing purposes.

**Review by ghost — APPROVED** [review]
Thanks

**Comment by javier-tercedor** [comment]
> @javier-tercedor @cdelgado5 Have you checked with distributors about this change? They were using this URL for testing purposes.

In the description of the related issue, we wrote that the current CM are not able to connect with the old one, related with a problem with the certificate for the old url. In fact this issue was created since Christian was talking about a new CM and this CM was not able to connect to the staging environment to test ARI.

That is the reason we have to update the documentation with the new URL.

Thanks for the warning Alejandro :)

**Comment by Shudrum** [comment]
~Labels please.~

**Comment by javier-tercedor** [comment]
> Labels please.

Hu Julien, this is the one I asked to you this morning. You told me that these rules does not apply to public repositories, in fact I am not able to see the list of our labels for this repo.

**Comment by Shudrum** [comment]
lol. I asked on multiple repositories and chained too fast. Sorry Javier ^^'

**Comment by javier-tercedor** [comment]
> lol. I asked on multiple repositories and chained too fast. Sorry Javier ^^'

no problem at all :D

**Pull request merged**
